# Generated by Django 4.2.29 on 2026-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
